import { StyleSheet } from 'react-native';
import { COLOR } from '../components/Colores';
export default StyleSheet.create({
    header:{
        backgroundColor:COLOR.azul,
        width:"115%",
        borderBottomRightRadius:100,
        height:"15%",//78
        marginLeft:-20
    },
    threeButtons:{
        width:"100%",
        height:"30%",
        flexDirection:'row',
        justifyContent:'space-between',
        marginTop:20
    },
    twoButtons:{
        width:"100%",
        height:"13%",
        flexDirection:'row',
        justifyContent:'space-between',
        marginTop:10
    },
    oneButton:{
        width:"100%",
        height:"15%",
        flexDirection:'row',
        justifyContent:'space-between',
        marginTop:10
    },
    columnas:{
        width:"100%",
        height:"100%",
        flexDirection:'column',
        justifyContent:'space-between',
        marginLeft:13
    },
    cuadradoInsideColumna:{
        width:"30%",
        height:"48%",
        borderRadius:10
    },
    rectangulo:{
        width:"65%",
        height:"100%",
        borderRadius:10
    },
    cuadrado:{
        width:"30%",
        height:"100%",
        borderRadius:10
    },
    actividades:{
        backgroundColor:'#00645C'
    },
    perfil:{
        backgroundColor:'#8CD7DF'
    },
    agenda:{
        backgroundColor:'#0E303F'
    },
    activo:{
        backgroundColor:'#8CD7DF'
    },
    completado10:{
        backgroundColor:'#F53F3F'
    },
    completado20:{
        backgroundColor:'#F26041'
    },
    completado30:{
        backgroundColor:'#F07143'
    },
    completado40:{
        backgroundColor:'#ED9545'
    },
    completado50:{
        backgroundColor:'#EBB246'
    },
    completado60:{
        backgroundColor:'#E8D348'
    },
    completado70:{
        backgroundColor:'#DBE64A'
    },
    completado85:{
        backgroundColor:'#ACE14D'
    },
    completado99:{
        backgroundColor:'#8DDE4E'
    },
    completado100:{
        backgroundColor:'#46D116'
    },
    reportes:{
        backgroundColor:'#5A8B91',
        width:"100%",
        height:"100%",
        borderRadius:10
    },
    servicioTecnico:{
        backgroundColor:'#476800'
    },
    cerrarSesion:{
        backgroundColor:COLOR.verde//'#7EB700'
    },
    text:{
        fontFamily:'BebasNeueBold',
        textAlign:'center',
        color:'white',
        fontSize: 20
    }
});