/**
 * @author Enrique Henriquez Figueroa
 * @copyright Binar10
 */
import { StyleSheet } from 'react-native';
import { COLOR } from '../components/Colores';
export default StyleSheet.create({
    gradient:{
        width:"115%",
        borderBottomRightRadius:100,
        height:"12.5%",
        marginLeft:-20
    },
    header:{
        backgroundColor:'transparent',
        // width:"115%",
        // borderBottomRightRadius:100,
        // height:"12.5%",//78
        // marginLeft:-20
    },
    threeButtons:{
        width:"100%",
        height:"30%",
        flexDirection:'row',
        justifyContent:'space-between',
        marginTop:20
    },
    twoButtons:{
        width:"100%",
        height:"13%",
        flexDirection:'row',
        justifyContent:'space-between',
        marginTop:10
    },
    oneButton:{
        width:"100%",
        height:"15%",
        flexDirection:'row',
        justifyContent:'space-between',
        marginTop:10
    },
    columnas:{
        width:"100%",
        height:"100%",
        flexDirection:'column',
        justifyContent:'space-between',
        marginLeft:13
    },
    cuadradoInsideColumna:{
        width:"30%",
        height:"48%",
        borderRadius:10
    },
    rectangulo:{
        width:"65%",
        height:"100%",
        borderRadius:10
    },
    cuadrado:{
        width:"30%",
        height:"100%",
        borderRadius:10
    },
    actividades:{
        backgroundColor:'#BDFAC9'
    },
    perfil:{
        backgroundColor:'#A3EAEC'
    },
    agenda:{
        backgroundColor:'#F1C5FF'
    },
    activo:{
        backgroundColor:'#C9A4FF'
    },
    completado10:{
        backgroundColor:COLOR.completado10
    },
    completado20:{
        backgroundColor:COLOR.completado20
    },
    completado30:{
        backgroundColor:COLOR.completado30
    },
    completado40:{
        backgroundColor:COLOR.completado40
    },
    completado50:{
        backgroundColor:COLOR.completado50
    },
    completado60:{
        backgroundColor:COLOR.completado60
    },
    completado70:{
        backgroundColor:COLOR.completado70
    },
    completado85:{
        backgroundColor:COLOR.completado85
    },
    completado99:{
        backgroundColor:COLOR.completado99
    },
    completado100:{
        backgroundColor:COLOR.completado100
    },
    reportes:{
        backgroundColor:'#FAD4BF',
        width:"100%",
        height:"100%",
        borderRadius:10
    },
    servicioTecnico:{
        backgroundColor:'#FDE396'
    },
    cerrarSesion:{
        backgroundColor:'#BDE26E'//'#7EB700'
    },
    text:{
        fontFamily:'BebasNeueBold',
        textAlign:'center',
        color:'white',
        fontSize: 20
    }
});