import { api } from '../services/api';

export const Imagen = {
    avatar: 'https://png.pngtree.com/svg/20160304/ajb_address_book_user_avatar_183015.png',
    avatar2: 'https://assets4.domestika.org/project-items/001/228/844/sesion-estudio-barcelona-10-big.jpg?1425034585',
    noDisponible: api.ipIcons + 'icono-supp-01.png',
    unidrogas: require('../../assets/unidrogas.png'),
    home: require('../../assets/Icons/icono-supp-03.png'),
    actividad: require('../../assets/Icons/icono-sup-02.png'),
    perfil: require('../../assets/Icons/icono-sup-08.png'),
    agenda: require('../../assets/Icons/icono-sup-04.png'),
    activo: require('../../assets/Icons/icono-sup-07.png'),
    inactivo: require('../../assets/Icons/icono-sup-06.png'),
    reportes: require('../../assets/Icons/icono-sup-03.png'),
    servicioTecnico: require('../../assets/Icons/icono-sup-09.png'),
    cerrarSesion: require('../../assets/Icons/icono-sup-05.png'),
    user: require('../../assets/Icons/icono-suppp-01.png'),
    pass: require('../../assets/Icons/icono-suppp-03.png'),
    back: require('../../assets/Icons/icono-supp-02.png'),
    phone: require('../../assets/Icons/icono-suppp-02.png'),
    mail: require('../../assets/Icons/icono-suppp-04.png'),
    code: require('../../assets/Icons/icono-suppp-05.png'),
    find: require('../../assets/Icons/icono-supppp-04.png'),
    check: require('../../assets/Icons/icono-supppp-01.png'),
    uncheck: require('../../assets/Icons/icono-supppp-02.png'),
    equis: require('../../assets/Icons/icono-supppp-03.png'),
    profileBorder: require('../../assets/Icons/icono-sup-01.png'),
    tuto1: require('../../assets/Images/tuto1.png'),
    tuto2: require('../../assets/Images/tuto2.png'),
    tuto3: require('../../assets/Images/tuto3.png'),
    tuto4: require('../../assets/Images/tuto4.png'),
    tuto5: require('../../assets/Images/tuto5.png'),
}